apps/catalog/urls.py
from django.urls import path, re_path
from apps.catalog import views

app_name = 'catalog'


urlpatterns = [
    path('', views.CatalogListView.as_view(), name='main'),
    path('detail/ajax-comment/<name>', views.AjaxComment.as_view(), name='comment'),
    path('category/<category>', views.SelectedCategoriesView.as_view(), name='category'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('detail/<name>', views.ProductView.as_view(), name='toy'),
    path('orders/', views.AjaxCart.as_view()),
    path('api/products', views.ProductAPIList.as_view()),
    path('api/product/<id>', views.ProductAPIView.as_view()),
    path('api/categories', views.CategoryAPIList.as_view()),
    path('api/materials', views.MaterialAPIList.as_view()),
    path('api/brands', views.BrandAPIList.as_view())
]

apps/company/urls.py
from django.urls import path
from apps.company import views

app_name = 'company'

urlpatterns = [
    path('', views.HomeView.as_view(), name='Home'),
    path('contacts', views.ContactsView.as_view(), name='Contacts')
]

apps/payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('ajax/cities/', views.AjaxCitiesView.as_view()),
    path('ajax/delete-order', views.AjaxDeleteOrderView.as_view()),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('<str:pk>', views.OrderView.as_view(), name='order'),
    path('my-orders/', views.OrdersList.as_view(), name='orders-list'),
]

apps/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as reset
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'users'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='Log in'),
    path('sign_up', views.SignUpView.as_view(), name='Sign up'),
    path(
        'reset_password',
        reset.PasswordResetView.as_view(
            template_name='users/reset_password/send_mail.html',
            email_template_name='users/reset_password/mail.html',
            success_url=reverse_lazy('users:Success'),
            from_email='oleksandr.hnylosyr@gmail.com'
        ),
        name='Reset password'
    ),
    path('success', views.SendingSuccessFul.as_view(), name='Success'),
    path(
        'change_password/<uidb64>/<token>/',
        reset.PasswordResetConfirmView.as_view(
            template_name='users/reset_password/change_password.html', success_url=reverse_lazy('users:Log in')
        ),
        name='password_reset_confirm'
    ),
    path('logout/', views.LogoutView.as_view(), name='Log out'),
    path('profile', login_required(views.ProfileView.as_view()), name='Profile'),
    path('ajax_sign_up', views.AjaxSignUpViews.as_view()),
    # path('orders', views.AjaxShowOrder.as_view())
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.company.urls')),
    path('account/', include('apps.users.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('catalog/', include('apps.catalog.urls'),),
    path('pages', include('django.contrib.flatpages.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('apps.payment.urls', namespace='payment')),
    path('captcha/', include('captcha.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/company/models.py
from django.db import models


class Contacts(models.Model):
    full_name = models.CharField(verbose_name='Full name', max_length=25, unique=True)
    email = models.EmailField(verbose_name='Email')

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name_plural = 'Contacts'

apps/company/forms.py
from django import forms
from .models import Contacts


class ContactsForm(forms.ModelForm):
    class Meta:
        model = Contacts
        fields = '__all__'

        widgets = {
            'full_name': forms.TextInput(attrs={
                'class': 'contacts__input',
                'id': 'name',
                'placeholder': 'Enter your full name'
            }),
            'email': forms.TextInput(attrs={
                'class': 'contacts__input',
                'id': 'email',
                'placeholder': 'Enter your email'
            })
        }

apps/company/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView
from django.core.mail import send_mail
from .forms import ContactsForm


class HomeView(TemplateView):
    template_name = 'company/home.html'


class ContactsView(CreateView):
    template_name = 'company/contacts.html'
    form_class = ContactsForm
    success_url = reverse_lazy('company:Contacts')

    def form_valid(self, form):
        send_mail(
            'Thank for your subscribe', 'We will send you massages about our products',
            'oleksandr.hnylosyr@gmail.com', [form.cleaned_data['email']]
        )

        return super().form_valid(form)

frontend/templates/company/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contacts</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/company/contacts.css' %}">
</head>
<body>
    <header class="header">
        <div class="wrapper">
            <div class="header__inner">
                <div class="logo">
                    <a href="{% url 'company:Home' %}" class="logo__link">
                        hytor
                    </a>
                </div>
            </div>
        </div>
    </header>
    <main class="main">
        <section class="contacts">
            <div class="wrapper-small">
                <div class="contacts__inner">
                    <form class="contacts__form" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <label for="{{field.id_for_label}}" class="contacts__label">{{field.label}}:</label>
                            {{field}}
                            {% if field.errors %}
                                {{field.errors}}
                            {% endif %}
                        {% endfor %}
                        <button class="contacts__btn">Send</button>
                    </form>
                </div>
            </div>
        </section>
    </main>
</body>
</html>

frontend/templates/company/home.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HYTOR</title>
    <link rel="stylesheet" href="static/css/company/home.css">
    <link rel="stylesheet" href="static/css/cart.css">
    <link rel="stylesheet" href="static/css/profile.css">
</head>
<body class="page">
    <header class="header">
        <div class="wrapper">
            <div class="header__inner">
                <div class="logo">
                    <a href="#" class="logo__link">
                        hytor
                    </a>
                </div>
                <div class="toggle-menu">
                    <nav class="menu">
                        <ul class="menu__list">
                            <li class="menu__item">
                                <a href="#" class="menu__link" id="products">Our products</a>
                            </li>
                            <li class="menu__item">
                                <a href="#" class="menu__link" id="about">about us</a>
                            </li>
                            <li class="menu__item">
                                <a href="#" class="menu__link" id="contacts">Contacts</a>
                            </li>
                            <li class="menu__item">
                                <a href="{% url 'catalog:main' %}" class="menu__link">catalog</a>
                            </li>
                        </ul>
                    </nav>
                    {% if request.user.is_authenticated %}
                    <div class="profile">
                        <img src="static/img/company/profile.png" alt="Profile" class="profile__img">
                        <ul class="profile__list">
                            <li class="profile__item"><a href="{% url 'users:Profile'%}" class="profile__link">My profile</a></li>
                            <li class="profile__item"><a href="{% url 'payment:orders-list' %}" class="profile__link">Orders</a></li>
                            <li class="profile__item logout"><a href="{% url 'users:Log out'%}" class="profile__link">Log out</a></li>
                        </ul>
                    </div>
                    {% else %}
                        <a href="{% url 'users:Log in' %}" class="header__btn">Sign in</a>
                    {% endif %}
                    <div class="cart">
                        <a href="#" class="cart__link">
                            <img class="cart__img" src="static/img/basket.png" alt="Cart">
                            {% if cart_length %}
                                 <span class="cart__badge">{{cart_length}}</span>
                            {% endif %}
                        </a>
                    </div>
                </div>
                <div class="header__burger burger">
                    <span class="burger__line"></span>
                    <span class="burger__line"></span>
                    <span class="burger__line"></span>
                </div>
            </div>
        </div>
    </header>
    <main class="main">
        <div class="wrapper">
            <section class="intro">
                <h1 class="intro__title">Our shop have many toys which will like your child</h1>
                <p class="intro__text">We promise that you will be pleased </p>
                <a href="{% url 'catalog:main' %}" class="intro__btn">Look at our catalog</a>
            </section>
            <section class="products">
                <h1 class="products__title">Our products</h1>
                <div class="products__items">
                    <div class="products__item">
                        <img src="static/img/company/quality.png" alt="quality" class="products__img">
                        <p class="products__text">
                            We have high quility products
                        </p>
                    </div>
                    <div class="products__item">
                        <img src="static/img/company/complete.png" alt="complete" class="products__img">
                        <p class="products__text">We have more 1 milion oreders</p>
                    </div>
                    <div class="products__item">
                        <img src="static/img/company/delivery.png" alt="delivery" class="products__img">
                        <p class="products__text">
                            You get your order within three days a week
                        </p>
                    </div>
                </div>
            </section>
            <section class="about">
                <h4 class="about__title">Our assortment amount more 3 thousand toys</h4>
                <p class="about__text">
                    We started at 2012 and still the leader in the sales of toys.
                    We love to give children our toys and we know how to make that your children will laugh.
                </p>
                <img src="static/img/company/children.png" alt="Children" class="about__img">
            </section>
        </div>
        <div class="orders">
        <div class="orders__inner">

            <div class="orders__top">
                <h2 class="orders__top-title">Cart</h2>
                <div class="orders__exit"></div>
            </div>
            <div class="orders__bottom">
                <div class="orders__list">
                    {% for id, item in cart.items %}
                        <div class="orders__list-item" data-product-id="{{id}}">
                            <div class="orders__block orders__block--left">
                                <img src="{{item.poster}}" alt="Poster of toy" class="orders__img">
                                <div class="order__info">
                                    <h3 class="orders__title">{{item.name}}</h3>
                                    <div class="orders__price">{{item.totalPrice}}$</div>
                                </div>
                            </div>
                            <div class="orders__block orders__block--right">
                                <div class="orders__btn-delete">Delete</div>
                                <div class="quantity">
                                    <button class="quantity__btn" id="minus">-</button>
                                    <input type="number" class="quantity__input"  value="{{item.quantity}}">
                                    <button class="quantity__btn" id="plus">+</button>
                                </div>
                                <a href="{% url 'payment:order' id %}" class="orders__btn-buy">Buy</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </main>
    <footer class="footer">
        <div class="wrapper">
            <div class="footer__inner">
                <ul class="social">
                    <li class="social__item"><a href="" class="social__link"><img src="static/img/company/instagram.png" alt="Instagram" class="social__img"></a>
                    </li>
                    <li class="social__item"><a href="" class="social__link"><img src="static/img/company/facebook.png" alt="Facebook" class="social__img"></a>
                    </li>
                    <li class="social__item"><a href="" class="social__link"><img src="static/img/company/in.png" alt="LinkedIn" class="social__img"></a>
                    </li>
                    <li class="social__item"><a href="" class="social__link"><img src="static/img/company/vk.png" alt="VK" class="social__img"></a>
                    </li>
                </ul>
                <div class="footer__block">
                    <a href="tel:+380734409269" class="phone">+380734409269</a>
                    <a href="mailto:oleksandr.hnylosyr@gmail.com" class="email">oleksandr.hnylosyr@gmail.com</a>
                </div>
            </div>
        </div>
    </footer>
    <div class="order__list">
        
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="static/js/profile.js"></script>
    <script src="static/js/company/home.js"></script>
    <script src="static/js/cart.js"></script>
</body>
</html>