apps/company/urls.py
from django.urls import path
from apps.company import views

app_name = 'company'

urlpatterns = [
    path('', views.HomeView.as_view(), name='Home'),
    path('contacts', views.ContactsView.as_view(), name='Contacts')
]

apps/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as reset
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'users'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='Log in'),
    path('sign_up', views.SignUpView.as_view(), name='Sign up'),
    path(
        'reset_password',
        reset.PasswordResetView.as_view(
            template_name='users/reset_password/send_mail.html',
            email_template_name='users/reset_password/mail.html',
            success_url=reverse_lazy('users:Success'),
            from_email='oleksandr.hnylosyr@gmail.com'
        ),
        name='Reset password'
    ),
    path('success', views.SendingSuccessFul.as_view(), name='Success'),
    path(
        'change_password/<uidb64>/<token>/',
        reset.PasswordResetConfirmView.as_view(
            template_name='users/reset_password/change_password.html', success_url=reverse_lazy('users:Log in')
        ),
        name='password_reset_confirm'
    ),
    path('logout/', views.LogoutView.as_view(), name='Log out'),
    path('profile', login_required(views.ProfileView.as_view()), name='Profile'),
    path('ajax_sign_up', views.AjaxSignUpViews.as_view()),
    # path('orders', views.AjaxShowOrder.as_view())
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.company.urls')),
    path('account/', include('apps.users.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('catalog/', include('apps.catalog.urls'),),
    path('pages', include('django.contrib.flatpages.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('apps.payment.urls', namespace='payment')),
    path('captcha/', include('captcha.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.utils import timezone


class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **other_fields):
        other_fields.setdefault("is_staff", False)
        other_fields.setdefault("is_superuser", False)
        user = self.model(
            username=username,
            email=self.normalize_email(email),
            **other_fields
        )
        if password:
            user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        user = self.create_user(
            username=username,
            email=email,
            password=password,
            **other_fields
        )
        if other_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if other_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        verbose_name='Username', db_index=True, max_length=20,
        help_text='Enter your username', unique=True
    )
    first_name = models.CharField(verbose_name='First name', max_length=20, help_text='Enter your name', null=True)
    last_name = models.CharField(verbose_name='Last name', max_length=20, help_text='Enter your surname')
    email = models.EmailField(verbose_name='Email:', help_text='Enter your email', unique=True)
    sex = models.CharField(
        verbose_name='Sex', max_length=6,
        choices=[('Female', 'Female'), ('Male', 'Male')], null=True
    )
    password = models.CharField(
        verbose_name='Password:', max_length=126,
        help_text='Enter your password'
    )
    date_joined = models.DateTimeField(verbose_name="date joined", default=timezone.now, editable=False)
    is_staff = models.BooleanField(verbose_name='Staff', default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(verbose_name='Superuser', default=False)
    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    objects = CustomUserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        return '{0} {1}'.format(self.first_name, self.last_name)

    def short_name(self):
        return self.first_name

    def __str__(self):
        return self.username

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)


# class OrderItem(models.Model):
#     toy = models.ForeignKey('catalog.Toy', verbose_name='Toy', on_delete=models.CASCADE, related_query_name='orders')
#     user = models.ForeignKey(CustomUser, verbose_name='User', on_delete=models.CASCADE, related_name='orders')
#     quantity = models.PositiveIntegerField(verbose_name='Count', default=1)
#
#     def get_cost(self):
#         return self.quantity * self.toy.objects.all().price
#
#     def __str__(self):
#         return self.toy

apps/users/forms.py
from django import forms
from .models import CustomUser
from captcha.fields import CaptchaField


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email:', widget=forms.EmailInput(attrs={
        'class': 'form__input',
        'placeholder': 'Email',
        'id': 'email'
    }))
    password = forms.CharField(label='Password:', widget=forms.PasswordInput(attrs={
        'class': 'form__input',
        'placeholder': 'Password',
        'id': 'Password'
    }))
    captcha = CaptchaField(label='Captcha')


class ResetPasswordForm(forms.Form):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'form__input',
        'id': 'email'
    }))


class ChangePasswordForm(forms.Form):
    password1 = forms.CharField(label='Password', max_length=16, min_length=8, widget=forms.PasswordInput(attrs={
        'class': 'form__input',
        'placeholder': 'Password',
        'id': 'Password'
    }))
    password2 = forms.CharField(label='Repeat password', max_length=16, min_length=8, widget=forms.PasswordInput(attrs={
        'class': 'form__input',
        'placeholder': 'Password',
        'id': 'Password'
    }))

    def clean(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 != password2:
            return None
        else:
            return self.cleaned_data


class SignUpForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'last_name', 'first_name', 'email', 'sex', 'password']
        widgets = {
            'email': forms.EmailInput(attrs={
                'class': 'form__input',
                'placeholder': 'example@email.com',
                'id': 'email'
            }),
            'username': forms.TextInput(attrs={
                'class': 'form__input',
                'placeholder': 'Username',
                'id': 'username'
            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form__input',
                'placeholder': 'First_name',
                'id': 'first_name'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form__input',
                'placeholder': 'Last_name',
                'id': 'last_name'
            }),
            'sex': forms.Select(attrs={
                'class': 'form__input',
                'id': 'sex'
            }),
            'password': forms.PasswordInput(attrs={
                'class': 'form__input',
                'placeholder': 'Password',
                'id': 'Password'
            })
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'last_name', 'first_name', 'email', 'sex']
        widgets = {
            'email': forms.EmailInput(attrs={
                'class': 'form__input',
                'placeholder': 'example@email.com',
                'id': 'email'
            }),
            'username': forms.TextInput(attrs={
                'class': 'form__input',
                'placeholder': 'Username',
                'id': 'username'
            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form__input',
                'placeholder': 'First_name',
                'id': 'first_name'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form__input',
                'placeholder': 'Last_name',
                'id': 'last_name'
            }),
            'sex': forms.Select(attrs={
                'class': 'form__input',
                'id': 'sex'
            }),
            'password': forms.PasswordInput(attrs={
                'class': 'form__input',
                'placeholder': 'Password',
                'id': 'Password'
            })
        }

apps/users/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.views.generic import FormView, RedirectView, UpdateView, TemplateView, View
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from .forms import *
from .models import *


class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('company:Home')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(email=email, password=password)
        if user:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return render(self.request, 'users/login.html', context={
                'error': 'Don`t correct email or password.',
                'form': LoginForm
            })


class SignUpView(FormView):
    template_name = 'users/signup.html'
    form_class = SignUpForm
    form_class.fields = ['username', 'last_name', 'first_name', 'email', 'sex', 'password']
    success_url = reverse_lazy('company:Home')

    def form_valid(self, form):
        data = form.cleaned_data
        email = data.pop('email')
        password = data.pop('password')
        CustomUser.objects.create_user(email=email, password=password, **data)
        return super(SignUpView, self).form_valid(form)


class LogoutView(RedirectView):
    pattern_name = 'company:Home'
    
    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        return super(LogoutView, self).get_redirect_url(*args, **kwargs)


class ProfileView(UpdateView):
    template_name = 'users/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('users:Profile')

    def get_object(self, queryset=None):
        username = self.request.user.username
        self.user = get_object_or_404(CustomUser, username=username)
        return self.user

    def get_initial(self):
        initial = {
            'username': self.user.username,
            'last_name': self.user.last_name,
            'first_name': self.user.first_name,
            'email': self.user.email,
            'sex': self.user.sex
        }

        return initial


class SendingSuccessFul(TemplateView):
    template_name = 'users/reset_password/success.html'


class AjaxSignUpViews(FormView):
    form_class = SignUpForm
    template_name = 'users/signup.html'

    def form_invalid(self, form):
        response = {}
        for field, error in form.errors.items():
            response[field] = error
        return JsonResponse({'response': response, 'result': 'Error'})


# class AjaxShowOrder(View):
#     def get(self, request, *args, **kwargs):
#         response = Product.objects.filter(orders__user=self.request.user).values()
#         return JsonResponse({'response': list(response)})

frontend/templates/users/reset_password/change_password.html
{% extends 'users/reset_password/reset_password.html' %}
{% block content %}
{% if request.user.is_authenticated %}
    <div class="authenticated">
        <p class="authenticated__text">
            You have already authenticated. Do you want to logout
        </p>
        <a href="{% url 'users:Log out' %}" class="authenticated__link">Log out</a>
    </div>
{% else %}
    {% if error %}
        <p class="error">{{error}}</p>
    {% endif %}
    <form method="POST" class="form">
        {% csrf_token %}
        <label class="form__label" for="{{form.new_password1.id_for_label}}">{{form.new_password1.label}}</label>
        {{form.new_password1}}
        {% if form.new_password1.errors %}
            {{form.new_password1.errors}}
        {% endif %}
        <label class="form__label" for="{{form.new_password2.id_for_label}}">{{form.new_password2.label}}</label>
        {{form.new_password2}}
        {% if form.new_password2.errors %}
            {{form.new_password2.errors}}
        {% endif %}
        <input type="submit" value="Send" class="submit">
    </form>
{% endif %}
{% endblock %}

frontend/templates/users/reset_password/mail.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
{% translate "Thanks for using our site!" %}
{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

frontend/templates/users/reset_password/reset_password.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Reset password</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/users/reset_password.css' %}">
</head>
<body>
    <header class="header">
        <div class="wrapper">
            <div class="header__inner">
                <div class="logo">
                    <a href="{% url 'company:Home' %}" class="logo__link">
                        hytor
                    </a>
                </div>
            </div>
        </div>
    </header>
    <main class="main">
        <section class="reset">
            <div class="reset__inner">
                {% block content %}
                {% endblock %}
            </div>
        </section>
    </main>
</body>
</html>

frontend/templates/users/reset_password/send_mail.html
{% extends 'users/reset_password/reset_password.html' %}
{% block content %}
{% if request.user.is_authenticated %}
    <div class="authenticated">
        <p class="authenticated__text">
            You have already authenticated. Do you want to log out?
        </p>
        <a href="{% url 'users:Log out' %}" class="authenticated__link">Log out</a>
    </div>
{% else %}
    {% if error %}
        <p class="error">{{error}}</p>
    {% endif %}
    <form method="POST" class="form" action="">
        <h4 class="reset__title">Enter your user account's verified email address and we will send you a password reset link.</h4>
        {% csrf_token %}
        <label class="form__label" for="{{form.email.id_for_label}}">{{form.email.label}}</label>
        {{form.email}}
        {% if form.email.errors %}
            {{form.email.errors}}
        {% endif %}
        <input type="submit" value="Send" class="submit">
    </form>
        <a href="{% url 'users:Log in' %}" class="reset__link">Do you remember your password?Log in</a>
{% endif %}
{% endblock %}

frontend/templates/users/reset_password/success.html
{% extends 'users/reset_password/reset_password.html' %}
{% block content %}
    <h1 class="success-title">We have sent a letter to your email address. You can close this tab</h1>
{% endblock %}