apps/catalog/urls.py
from django.urls import path, re_path
from apps.catalog import views

app_name = 'catalog'


urlpatterns = [
    path('', views.CatalogListView.as_view(), name='main'),
    path('detail/ajax-comment/<name>', views.AjaxComment.as_view(), name='comment'),
    path('category/<category>', views.SelectedCategoriesView.as_view(), name='category'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('detail/<name>', views.ProductView.as_view(), name='toy'),
    path('orders/', views.AjaxCart.as_view()),
    path('api/products', views.ProductAPIList.as_view()),
    path('api/product/<id>', views.ProductAPIView.as_view()),
    path('api/categories', views.CategoryAPIList.as_view()),
    path('api/materials', views.MaterialAPIList.as_view()),
    path('api/brands', views.BrandAPIList.as_view())
]

apps/company/urls.py
from django.urls import path
from apps.company import views

app_name = 'company'

urlpatterns = [
    path('', views.HomeView.as_view(), name='Home'),
    path('contacts', views.ContactsView.as_view(), name='Contacts')
]

apps/payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('ajax/cities/', views.AjaxCitiesView.as_view()),
    path('ajax/delete-order', views.AjaxDeleteOrderView.as_view()),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('<str:pk>', views.OrderView.as_view(), name='order'),
    path('my-orders/', views.OrdersList.as_view(), name='orders-list'),
]

apps/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as reset
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'users'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='Log in'),
    path('sign_up', views.SignUpView.as_view(), name='Sign up'),
    path(
        'reset_password',
        reset.PasswordResetView.as_view(
            template_name='users/reset_password/send_mail.html',
            email_template_name='users/reset_password/mail.html',
            success_url=reverse_lazy('users:Success'),
            from_email='oleksandr.hnylosyr@gmail.com'
        ),
        name='Reset password'
    ),
    path('success', views.SendingSuccessFul.as_view(), name='Success'),
    path(
        'change_password/<uidb64>/<token>/',
        reset.PasswordResetConfirmView.as_view(
            template_name='users/reset_password/change_password.html', success_url=reverse_lazy('users:Log in')
        ),
        name='password_reset_confirm'
    ),
    path('logout/', views.LogoutView.as_view(), name='Log out'),
    path('profile', login_required(views.ProfileView.as_view()), name='Profile'),
    path('ajax_sign_up', views.AjaxSignUpViews.as_view()),
    # path('orders', views.AjaxShowOrder.as_view())
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.company.urls')),
    path('account/', include('apps.users.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('catalog/', include('apps.catalog.urls'),),
    path('pages', include('django.contrib.flatpages.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('apps.payment.urls', namespace='payment')),
    path('captcha/', include('captcha.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/catalog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import os


def get_poster_path(obj, filename):
    return os.path.join('catalog', str(obj.name), filename)


def get_photos_path(obj, filename):
    return os.path.join('catalog', str(obj.product.name), filename)


class Product(models.Model):
    name = models.CharField(verbose_name='Name', max_length=40, db_index=True, unique=True)
    description = models.CharField(verbose_name='Describe your toys', max_length=2000)
    created = models.DateField(verbose_name='Created')
    material = models.ManyToManyField('Material', verbose_name='Materials')
    poster = models.ImageField(verbose_name='Poster', default=f'media/catalog/Unknown.png', upload_to=get_poster_path)
    brand = models.ForeignKey(
        'Brand', verbose_name='Brand', related_name='brands',
        on_delete=models.CASCADE, default=[0]
    )
    age = models.IntegerField(verbose_name='Age', default=0)
    country = models.ForeignKey(
        'cities_light.Country', verbose_name='Country',
        on_delete=models.SET_DEFAULT, default=[0],
        related_name='countries'
    )
    quantity = models.IntegerField(verbose_name='Quantity', default=0)
    price = models.FloatField(verbose_name='Price', default=0)
    category = models.ManyToManyField('Category', verbose_name='Category', default=[0], related_name='categories')

    def get_id(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('catalog:toy', kwargs={'name': self.name})

    @property
    def available(self):
        return True if self.quantity else False

    def get_first_image(self):
        return self.photos.all()[0].image.url

    def __str__(self):
        return self.name


class Category(models.Model):
    category = models.CharField(verbose_name='Category', max_length=25, unique=True)

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Review(models.Model):
    comment = models.CharField(verbose_name='Comment', max_length=256, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='User', on_delete=models.CASCADE)
    review = models.ForeignKey('Product', verbose_name='Product', related_name='reviews', on_delete=models.CASCADE)

    def __str__(self):
        return self.comment


class Photo(models.Model):
    image = models.ImageField(verbose_name='Image', upload_to=get_photos_path)
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='photos')


class Brand(models.Model):
    brand = models.CharField(verbose_name='Brand', max_length=40, unique=True)

    def __str__(self):
        return self.brand


class Material(models.Model):
    material = models.CharField(verbose_name='Material', max_length=16, unique=True)

    def __str__(self):
        return self.material

apps/catalog/forms.py
from django import forms
from .models import *


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

apps/catalog/views.py
from django.views.generic import DetailView, ListView, View
from django.http import HttpResponse, JsonResponse
from django.db.models import Q
from django.http import QueryDict
from rest_framework import generics
from .forms import *
from .cart import Cart
from .serializers import *



class CatalogListView(ListView):
    template_name = 'catalog/catalog.html'
    model = Product
    context_object_name = 'products'
    paginate_by = 5

    def get_queryset(self):
        return super(CatalogListView, self).get_queryset().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(CatalogListView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()

        return context


class AjaxCart(View):
    @staticmethod
    def post(request):
        return JsonResponse(Cart(request).post())

    @staticmethod
    def delete(request):
        Cart(request).delete()
        return JsonResponse({'cart_counter': len(Cart(request).display())})

    @staticmethod
    def put(request):
        return JsonResponse(Cart(request).put())


class SelectedCategoriesView(ListView):
    template_name = 'catalog/catalog.html'
    context_object_name = 'products'
    paginate_by = 5

    def get_queryset(self):
        return Product.objects.filter(category__category=self.kwargs['category']).order_by('id')

    def get_context_data(self, **kwargs):
        categories = Category.objects.all()
        context = super(SelectedCategoriesView, self).get_context_data(**kwargs)
        context['categories'] = categories
        return context


class SearchView(ListView):
    template_name = 'catalog/catalog.html'
    model = Product
    context_object_name = 'products'
    paginate_by = 5

    def get_queryset(self):
        return list(set(Product.objects.filter(
            Q(name__icontains=self.request.GET['query']) |
            Q(description__icontains=self.request.GET['query']) |
            Q(brand__brand__icontains=self.request.GET['query']) |
            Q(category__category__icontains=self.request.GET['query'])
        )))

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        items = Product.objects.filter(name__icontains=self.request.POST['query']).values_list('name')
        return JsonResponse({'items': list(items)})


class ProductView(DetailView):
    template_name = 'catalog/toy_detail.html'
    context_object_name = 'toy'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = self.kwargs['name']
        return context

    def get_object(self):
        return Product.objects.filter(name=self.kwargs['name'])


class AjaxComment(View):
    template_name = 'catalog/toy_detail.html'

    def post(self, request, *args, **kwargs ):
        review = Review()
        comment = request.POST['comment']
        toy = Product.objects.get(name=kwargs['name'])
        review.comment = comment
        review.user = request.user
        review.review = toy
        review.save()
        return JsonResponse({'index': review.id})

    def put(self, request, *args, **kwargs):
        data = QueryDict(request.body)
        comment = data['comment']
        index = data['index']
        Review.objects.filter(Q(pk=index) & Q(user=self.request.user)).update(comment=comment)
        return HttpResponse()

    def delete(self, request, *args, **kwargs):
        data = QueryDict(request.body)
        index = data['index']
        Review.objects.filter(Q(pk=index) & Q(user=self.request.user)).delete()
        return HttpResponse()


class ProductAPIList(generics.ListAPIView):
    serializer_class = ProductSerializer
    queryset = Product.objects.all()


class ProductAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    lookup_url_kwarg = 'id'


class CategoryAPIList(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class BrandAPIList(generics.ListAPIView):
    queryset = Brand.objects.all()
    serializer_class = BrandSerializer


class MaterialAPIList(generics.ListAPIView):
    queryset = Material.objects.all()
    serializer_class = MaterialSerializer

frontend/templates/catalog/catalog.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Catalog</title>
    <link rel="stylesheet" href="{% static 'css/catalog/catalog.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
</head>
<body>
    <header class="header">
        <div class="wrapper">
            <div class="header__inner">
                <div class="logo">
                    <a href="{% url 'company:Home' %}" class="logo__link">
                        hytor
                    </a>
                </div>
                <div class="search">
                     <form class="search__form" action="{% url 'catalog:search' %}" method="GET">
                        <input type="text" class="search__input" placeholder="Search" name="query">
                        <button class="search__btn">Search</button>
                    </form>
                    <div class="search__results"></div>
                </div>
                <div class="header__box">
                    {% if request.user.is_authenticated %}
                        <div class="profile">
                            <img src="{% static 'img/company/profile.png' %}" alt="Profile" class="profile__img">
                            <ul class="profile__list">
                                <li class="profile__item"><a href="{% url 'users:Profile'%}" class="profile__link">My profile</a></li>
                                <li class="profile__item"><a href="#" class="profile__link">Orders</a></li>
                                <li class="profile__item logout"><a href="{% url 'users:Log out'%}" class="profile__link">Log out</a></li>
                            </ul>
                        </div>
                    {% else %}
                        <a href="{% url 'users:Log in' %}" class="header__btn">Sign in</a>
                    {% endif %}
                    <div class="cart">
                        <a href="#" class="cart__link">
                            <img class="cart__img" src="{% static 'img/basket.png' %}" alt="Cart">
                            {% if cart_length %}
                                 <span class="cart__badge">{{cart_length}}</span>
                            {% endif %}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <main class="main">
        <section class="catalog">
            <div class="catalog__inner">
                <div class="categories">
                    <h1 class="category__title">Categories</h1>
                    {% for category in categories %}
                        <a href="{% url 'catalog:category' category.category %}" class="categories__link">{{category.category}}</a>
                    {% endfor %}
                </div>
                <div class="catalog__list">
                    {% for product in products %}
                        <a href="{{product.get_absolute_url}}" class="catalog__link">
                            <div class="product">
                                <img src="{{product.poster.url}}" alt="{{product.name}}" class="product__img">
                                <div class="product__content">
                                    <h2 class="product__title">{{product.name}}</h2>
                                    <div class="product__box">
                                        <div class="box__line">
                                            <div class="box__item">Released for sale:</div>
                                            <div class="box__item box__item--right">{{product.created}}</div>
                                        </div>
                                        <div class="box__line">
                                            <div class="box__item">Catagory:</div>
                                            <div class="box__item">
                                                {% for category in product.category.all %}
                                                    {{category}}<br>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <dl class="description">
                                            <dt class="description__title">Description</dt>
                                            <dd class="description__text">{{ product.description|truncatewords:15 }}</dd>
                                        </dl>
                                        <div class="price">
                                            ${{product.price}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    {% empty %}
                        <div class="empty">
                            Haven`t added toys yet.
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <section class="pagination">
            <div class="wrapper">
                <div class="pagination__inner">
                   {% if page_obj.has_previous %}
                        <span class="page">
                            <a href="?page={{page_obj.previous_page_number}}"  class="pagination__link">{{page_obj.previous_page_number}}</a>
                        </span>
                    {% endif %}
                    <span class="page">
                        {{page_obj.number}}
                    </span>
                    {% if page_obj.has_next %}
                        <span class="page">
                            <a href="?page={{page_obj.next_page_number}}"  class="pagination__link">{{page_obj.next_page_number}}</a>
                        </span>
                        {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
                            <span class="page">
                            <a href="?page={{page_obj.page_obj.paginator.num_pages}}" class="pagination__link">{{page_obj.paginator.num_pages}}</a>
                            </span>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </section>
    </main>
    <div class="orders">
        <div class="orders__inner">
            <div class="orders__top">
                <h2 class="orders__top-title">Cart</h2>
                <div class="orders__exit"></div>
            </div>
            <div class="orders__bottom">
                <div class="orders__list">
                    {% for id, item in cart.items %}
                        <div class="orders__list-item" data-product-id="{{id}}">
                            <div class="orders__block orders__block--left">
                                <img src="{{item.poster}}" alt="Poster of toy" class="orders__img">
                                <div class="order__info">
                                    <h3 class="orders__title">{{item.name}}</h3>
                                    <div class="orders__price">{{item.totalPrice}}$</div>
                                </div>
                            </div>
                            <div class="orders__block orders__block--right">
                                <div class="orders__btn-delete">Delete</div>
                                <div class="quantity">
                                    <button class="quantity__btn" id="minus">-</button>
                                    <input type="number" class="quantity__input"  value="{{item.quantity}}">
                                    <button class="quantity__btn" id="plus">+</button>
                                </div>
                                <a href="{% url 'payment:order' id %}" class="orders__btn-buy">Buy</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/cart.js' %}"></script>
    <script src="{% static 'js/profile.js' %}"></script>
    <script src="{% static 'js/catalog/search.js' %}"></script>
</body>
</html>